import * as fs from 'fs'
import * as path from 'path'

interface FeatureFlags {
  onlineOrdering: boolean
  deliveryManagement: boolean
  tableReservations: boolean
  kitchenDisplay: boolean
  posIntegration: boolean
  inventoryManagement: boolean
  loyaltyProgram: boolean
  qrMenu: boolean
  smsNotifications: boolean
  whatsappAutomation: boolean
  aiChatbot: boolean
  advancedAnalytics: boolean
}

const DEFAULT_FLAGS: FeatureFlags = {
  onlineOrdering: false,
  deliveryManagement: false,
  tableReservations: false,
  kitchenDisplay: false,
  posIntegration: false,
  inventoryManagement: false,
  loyaltyProgram: false,
  qrMenu: false,
  smsNotifications: false,
  whatsappAutomation: false,
  aiChatbot: false,
  advancedAnalytics: false,
}

function loadFeatures(): FeatureFlags {
  // Try loading from features.json first (generated by inject.ts)
  const jsonPath = path.resolve(__dirname, 'features.json')
  if (fs.existsSync(jsonPath)) {
    try {
      const raw = fs.readFileSync(jsonPath, 'utf-8')
      return { ...DEFAULT_FLAGS, ...JSON.parse(raw) }
    } catch {
      // fall through to env vars
    }
  }

  // Fallback to environment variables
  return {
    onlineOrdering: process.env.FEATURE_ONLINE_ORDERING === 'true',
    deliveryManagement: process.env.FEATURE_DELIVERY_MANAGEMENT === 'true',
    tableReservations: process.env.FEATURE_TABLE_RESERVATIONS === 'true',
    kitchenDisplay: process.env.FEATURE_KITCHEN_DISPLAY === 'true',
    posIntegration: process.env.FEATURE_POS_INTEGRATION === 'true',
    inventoryManagement: process.env.FEATURE_INVENTORY_MANAGEMENT === 'true',
    loyaltyProgram: process.env.FEATURE_LOYALTY_PROGRAM === 'true',
    qrMenu: process.env.FEATURE_QR_MENU === 'true',
    smsNotifications: process.env.FEATURE_SMS_NOTIFICATIONS === 'true',
    whatsappAutomation: process.env.FEATURE_WHATSAPP_AUTOMATION === 'true',
    aiChatbot: process.env.FEATURE_AI_CHATBOT === 'true',
    advancedAnalytics: process.env.FEATURE_ADVANCED_ANALYTICS === 'true',
  }
}

export const features = loadFeatures()

export function isFeatureEnabled(feature: keyof FeatureFlags): boolean {
  return features[feature] === true
}
