import * as fs from 'fs'
import * as path from 'path'

const CONFIG_PATH = path.resolve(__dirname, '../config/client.json')
const ENV_PATH = path.resolve(__dirname, '../.env')
const FEATURES_PATH = path.resolve(__dirname, '../src/config/features.json')

interface ClientConfig {
  branding: {
    appName: string
    primaryColor: string
    tagline: string
    logoUrl: string
  }
  features: Record<string, boolean>
  environment: Record<string, string>
  business: {
    currency: string
    timezone: string
    businessHours: { start: string; end: string }
    gstRate: number
    serviceChargeRate: number
    deliveryRadius: number
    minOrderAmount: number
    avgPrepTime: number
  }
}

function inject() {
  if (!fs.existsSync(CONFIG_PATH)) {
    console.log('[inject] No config/client.json found. Using .env.example defaults.')
    return
  }

  const raw = fs.readFileSync(CONFIG_PATH, 'utf-8')
  const config: ClientConfig = JSON.parse(raw)

  console.log(`[inject] Injecting config for: ${config.branding.appName}`)

  // 1. Generate .env file
  const envLines: string[] = [
    '# Auto-generated by scripts/inject.ts — DO NOT EDIT',
    `DATABASE_URL="${config.environment.DATABASE_URL || ''}"`,
    `JWT_SECRET="${config.environment.JWT_SECRET || 'change-me'}"`,
    'JWT_EXPIRES_IN="7d"',
    'JWT_REFRESH_EXPIRES_IN="30d"',
    'PORT=4000',
    `NODE_ENV="${process.env.NODE_ENV || 'production'}"`,
    `APP_NAME="${config.branding.appName}"`,
    `APP_URL="${config.environment.APP_URL || ''}"`,
    `API_URL="${config.environment.API_URL || ''}"`,
    `RAZORPAY_KEY_ID="${config.environment.RAZORPAY_KEY_ID || ''}"`,
    `RAZORPAY_KEY_SECRET="${config.environment.RAZORPAY_KEY_SECRET || ''}"`,
    `RAZORPAY_WEBHOOK_SECRET="${config.environment.RAZORPAY_WEBHOOK_SECRET || ''}"`,
    `RESEND_API_KEY="${config.environment.RESEND_API_KEY || ''}"`,
    `EMAIL_FROM="${config.environment.EMAIL_FROM || 'noreply@wonderos.in'}"`,
    'UPLOAD_DIR="./uploads"',
    'MAX_FILE_SIZE="10485760"',
    '',
    '# Feature Flags',
    ...Object.entries(config.features).map(
      ([key, val]) => `FEATURE_${key.replace(/([A-Z])/g, '_$1').toUpperCase()}="${val}"`
    ),
    '',
    '# Business Config',
    `BUSINESS_CURRENCY="${config.business.currency || 'INR'}"`,
    `BUSINESS_TIMEZONE="${config.business.timezone || 'Asia/Kolkata'}"`,
    `BUSINESS_HOURS_START="${config.business.businessHours?.start || '10:00'}"`,
    `BUSINESS_HOURS_END="${config.business.businessHours?.end || '23:00'}"`,
    `BUSINESS_GST_RATE="${config.business.gstRate || 5}"`,
    `BUSINESS_SERVICE_CHARGE_RATE="${config.business.serviceChargeRate || 10}"`,
    `BUSINESS_DELIVERY_RADIUS="${config.business.deliveryRadius || 10}"`,
    `BUSINESS_MIN_ORDER_AMOUNT="${config.business.minOrderAmount || 20000}"`,
    `BUSINESS_AVG_PREP_TIME="${config.business.avgPrepTime || 30}"`,
  ]

  fs.writeFileSync(ENV_PATH, envLines.join('\n'), 'utf-8')
  console.log(`[inject] .env written`)

  // 2. Generate features.json
  fs.mkdirSync(path.dirname(FEATURES_PATH), { recursive: true })
  fs.writeFileSync(FEATURES_PATH, JSON.stringify(config.features, null, 2), 'utf-8')
  console.log(`[inject] features.json written`)

  console.log('[inject] Done!')
}

inject()
